
version: '2'
services:

  es-node-1:
    image: "es-demo"
    ports:
      - "9200:9200"
      - "9300:9300"
      
  es-node-2:
    image: "es-demo"
    ports:
      - "9210:9200"
      - "9310:9300"    
  
  es-node-3:
    image: "es-demo"
    ports:
      - "9220:9200"
      - "9320:9300"